---
abstract: 'Perl metrics storage and processing engine'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Perl::Metrics2
name: Perl-Metrics2
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Class::Inspector: 1.23
  File::HomeDir: 0.82
  File::ShareDir: 1.00
  File::Spec: 0.80
  ORLite: 1.20
  ORLite::Migrate: 0.02
  Params::Util: 0.37
  perl: 5.8.5
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Perl-Metrics2
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Perl-Metrics2
version: 0.01
